### ISSUE TITLE
Update for latest chart.js

### ISSUE THREAD

**Issue by guguso** [coderbydesign/chart-js-rails#13]
Hy,
Can you apply my commit to update Chart.js to version 1.0.2.
Thanks a lot, there is some new features that i really need in this version.

Regards,
Augustin

**Comment by coderbydesign** [comment]
Hi Augustin,

I don't see a pull request for the update, did you submit one?

Thanks!

**Comment by guguso** [comment]
Sorry, i failed. It's done now

**Comment by coderbydesign** [comment]
Thanks so much! The new gem version 0.0.9 with your merge is now out in the wild.
