### ISSUE TITLE
Slightly different require line

### ISSUE THREAD

**Issue by ashmckenzie** [coderbydesign/chart-js-rails#2]
Hi,

I'm on Mac OSX / Rails 4.0 and I had to put the following in my application.js to get it to work:

``` javascript
//= require Chart
```

instead of:

``` javascript
//= require chart
```

:)

Ash.

**Comment by richxlau** [comment]
how does one require chartjs in rails 6? i tried everything and can't get it to work

**Comment by fa11enangel** [comment]
Don't use gems anymore for JS stuff. Use webpacker.
