### ISSUE TITLE
Update to the latest version 2.7.3

### ISSUE THREAD

**Issue by KevinColemanInc** [coderbydesign/chart-js-rails#28]
https://github.com/chartjs/Chart.js/releases

**Comment by coderbydesign** [comment]
Apologies on the neglect of this. 

0.1.7 is now published on RubyGems: https://rubygems.org/gems/chart-js-rails/versions/0.1.7 with Chartjs v2.8.0

**Comment by KevinColemanInc** [comment]
You can configure your git client (or github.com itself!) to trigger a release automatically with a new git tag.
